### update an existing patient entity
PUT localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe",
  "email": "JhD_Official@example.com",
  "address": "123 street",
  "dateOfBirth": "2000-12-10"
}
###