### Create a new patient entity
POST localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe with Kafka",
  "email": "Test_billing_M@example.com",
  "address": "123 street",
  "dateOfBirth": "2002-12-10",
  "registeredDate": "2025-12-25"
}

###